name: My First Workflow

on: push

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
  - uses: actions/checkout@v4

  - name: Print Hello
    run: echo "Hello"

  - name: Safe Step
    run: echo "Fixed"
