name: Main Pipeline

on:
  push:
    branches: [main]

jobs:
  test:
    uses: ./.github/workflows/reusable-build.yml

  docker:
    needs: test
    uses: ./.github/workflows/reusable-docker.yml
    secrets:
      docker_token: ${{ secrets.DOCKER_TOKEN }}

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying app 🚀"
