name: Build Test

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      result: success

    steps:
      - uses: actions/checkout@v4
      - run: echo "Building project"
      - run: echo "Tests passed"
