name: Secrets Demo

on: push

jobs:
  test-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Check Secret
        env:
          MYMSG: ${{ secrets.MY_SECRET_MESSAGE }}
        run: |
          if [ -n "$MYMSG" ]; then
            echo "The secret is set: true"
          else
            echo "The secret is set: false"
          fi
